//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assistente de registro de chatlog para o LSC.
        ///
        ///Versão instalada: {0} {1}
        ///Diretório de recursos: {2}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtro avançado.
        /// </summary>
        internal static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a porque os diretórios &quot;{0}&quot; já existem..
        /// </summary>
        internal static string AlreadyExistingDirectoriesWarning {
            get {
                return ResourceManager.GetString("AlreadyExistingDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar desabilitar a função de inicialização automática..
        /// </summary>
        internal static string AutoStartDisableError {
            get {
                return ResourceManager.GetString("AutoStartDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar habilitar a função de inicialização automática..
        /// </summary>
        internal static string AutoStartEnableError {
            get {
                return ResourceManager.GetString("AutoStartEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este recurso deixará de funcionar se você excluir ou mover o analisador para um local diferente..
        /// </summary>
        internal static string AutoStartWarning {
            get {
                return ResourceManager.GetString("AutoStartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar salvar automaticamente o log de bate-papo.
        ///
        ///Certifique-se de ter escolhido um diretório não-sistema para seu caminho de backup..
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao mover os arquivos de backup para o novo diretório..
        /// </summary>
        internal static string BackupMoveError {
            get {
                return ResourceManager.GetString("BackupMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Backup auto: {0}.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O backup automático foi DESLIGADO. Configure-o novamente se desejar usá-lo..
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A função de backup automático será desligada enquanto o diálogo de configurações estiver aberto e as novas configurações serão aplicadas somente quando você fechar o diálogo de configurações.
        ///
        ///Gostaria de continuar?.
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um diretório que não seja raiz para o local do seu diretório de backup..
        /// </summary>
        internal static string BadBackupPath {
            get {
                return ResourceManager.GetString("BadBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha um local de backup válido ou desative o backup automático..
        /// </summary>
        internal static string BadBackupPathSave {
            get {
                return ResourceManager.GetString("BadBackupPathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um diretório não raiz para o local do seu diretório RAGEMP..
        /// </summary>
        internal static string BadDirectoryPath {
            get {
                return ResourceManager.GetString("BadDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a b.
        /// </summary>
        internal static string BetaShort {
            get {
                return ResourceManager.GetString("BetaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} caracteres e {1} linhas.
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora atual: {0}.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu diretório RAGEMP foi encontrado automaticamente em {0}
        ///
        ///Por favor, procure o caminho correto manualmente se estiver incorreto ou se você tiver várias instalações RAGEMP..
        /// </summary>
        internal static string DirectoryFinder {
            get {
                return ResourceManager.GetString("DirectoryFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar encontrar automaticamente o local do seu diretório RAGEMP. Procure-o manualmente..
        /// </summary>
        internal static string DirectoryFinderError {
            get {
                return ResourceManager.GetString("DirectoryFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível detectar o caminho para o seu diretório RAGEMP, procure-o manualmente..
        /// </summary>
        internal static string DirectoryFinderNotFound {
            get {
                return ResourceManager.GetString("DirectoryFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações (Primeira vez).
        /// </summary>
        internal static string DirectoryFinderTitle {
            get {
                return ResourceManager.GetString("DirectoryFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFF.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ON.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ERRO.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://snapmatic.flextor.com.br.
        /// </summary>
        internal static string FacebrowserLink {
            get {
                return ResourceManager.GetString("FacebrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://ls-chronicles.com.br/forum/index.php?/topic/776-guia-usando-o-chatlog-e-seus-comandos.
        /// </summary>
        internal static string FeatureShowcaseLink {
            get {
                return ResourceManager.GetString("FeatureShowcaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar excluir o arquivo..
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você pode ter apenas uma palavra, número ou par de nomes válidos em cada linha se quiser filtrar seu log de bate-papo.
        ///Exemplo: Barco, $500, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma correspondência encontrada.
        ///
        ///Certifique-se de ter apenas uma palavra, número ou par de nomes válidos em cada linha.
        ///Exemplo: Barco, $500, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHintNoMatches {
            get {
                return ResourceManager.GetString("FilterHintNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma ou mais palavras foram ignoradas durante a operação de filtragem porque não estão em um formato válido.
        ///
        ///Certifique-se de ter apenas uma palavra, número ou par de nomes válidos em cada linha.
        ///Exemplo: Boat, $500, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHintSkipped {
            get {
                return ResourceManager.GetString("FilterHintSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chat log{0} carregado{1}.
        /// </summary>
        internal static string FilterLogStatus {
            get {
                return ResourceManager.GetString("FilterLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao ler o arquivo selecionado..
        /// </summary>
        internal static string FilterReadError {
            get {
                return ResourceManager.GetString("FilterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://ls-chronicles.com.br/forum.
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faça backup do registro de bate-papo automaticamente enquanto o jogo estiver em execução (a cada {0} {1}).
        /// </summary>
        internal static string IntervalHint {
            get {
                return ResourceManager.GetString("IntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}. (recomendado).
        /// </summary>
        internal static string IntervalRecommended {
            get {
                return ResourceManager.GetString("IntervalRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caminho do diretório RAGEMP inválido..
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha um local de diretório RAGEMP válido antes de tentar habilitar o backup automático..
        /// </summary>
        internal static string InvalidDirectoryPathBackup {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha um local válido no diretório RAGEMP antes de tentar filtrar seu registro de bate-papo..
        /// </summary>
        internal static string InvalidDirectoryPathFilter {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O idioma escolhido será usado para extrair o log de bate-papo do servidor correto.
        ///
        ///Isso significa que se você escolher inglês, você só poderá analisar o log de bate-papo gerado do servidor em inglês. Você precisará alterar o idioma do aplicativo se desejar analisar outros logs de bate-papo..
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a em {0}.
        /// </summary>
        internal static string LoadedAt {
            get {
                return ResourceManager.GetString("LoadedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 80.75.221.45_22005.
        /// </summary>
        internal static string MainIP {
            get {
                return ResourceManager.GetString("MainIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar o parser impedirá que os backups automáticos aconteçam.
        ///
        ///Você gostaria de minimizar o parser para a bandeja do sistema?.
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minutos.
        /// </summary>
        internal static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Minuto.
        /// </summary>
        internal static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gostaria de mover todos os seus arquivos de backup existentes para o novo diretório?.
        /// </summary>
        internal static string MoveBackups {
            get {
                return ResourceManager.GetString("MoveBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vários diretórios de recursos LSC foram encontrados. É aconselhável que você use um único IP para se conectar ao servidor e exclua o outro diretório de recursos.
        ///
        ///Mantenha &quot;{0}&quot; ou &quot;{1}&quot;..
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível encontrar o registro de chatlog..
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você ainda não carregou um registro de chatlog..
        /// </summary>
        internal static string NoChatLogLoaded {
            get {
                return ResourceManager.GetString("NoChatLogLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma atualização pôde ser encontrada.
        ///Tente verificar sua conexão de internet ou aumentar o tempo limite de verificação de atualização na janela de configurações.
        ///
        ///Versão instalada: {0}.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você ainda não filtrou nada..
        /// </summary>
        internal static string NothingFiltered {
            get {
                return ResourceManager.GetString("NothingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não moveu nenhum diretório para o novo local.
        /// </summary>
        internal static string NothingMovedWarning {
            get {
                return ResourceManager.GetString("NothingMovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você ainda não analisou nada..
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não inseriu nenhuma palavra para filtrar.
        ///
        ///Use o filtro simples se não quiser filtrar por palavras..
        /// </summary>
        internal static string NoWordsToFilter {
            get {
                return ResourceManager.GetString("NoWordsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um formato antigo foi detectado ao analisar o log de bate-papo e é aconselhável que você o exclua e todos os outros scripts que não foram atualizados corretamente.
        ///
        ///Você gostaria de excluir esses arquivos?
        ///(O arquivo de chatlog será analisado antes da exclusão).
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gostaria de abrir a página de documentação do analisador de log de bate-papo encontrado nos fóruns do LSC?.
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outra instância já está em execução, verifique sua barra de tarefas ou gerenciador de tarefas..
        /// </summary>
        internal static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao analisar o registro do chatlog..
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas os diretórios &quot;{0}&quot; foram movidos para o novo local.
        /// </summary>
        internal static string PartialMoveWarning {
            get {
                return ResourceManager.GetString("PartialMoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://github.com/yuribraga17/LSC-Log-Parser.
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Questão.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://github.com/yuribraga17/LSC-Log-Parser/releases.
        /// </summary>
        internal static string ReleasesLink {
            get {
                return ResourceManager.GetString("ReleasesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reiniciar.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você está executando a versão mais recente do analisador de log de bate-papo.
        ///
        ///Versão instalada: {0}.
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O mesmo log de bate-papo foi copiado {0} ou mais vezes, o que significa que o script do cliente RAGEMP responsável por registrar seu bate-papo está quebrado.
        ///
        ///Isso acontece quando você perde a conexão com a internet ou o servidor trava. A única maneira conhecida de corrigir o problema é excluindo os diretórios de recursos do servidor em que você está jogando.
        ///
        ///Os logs de bate-papo perdidos não podem ser recuperados..
        /// </summary>
        internal static string SameHashWarning {
            get {
                return ResourceManager.GetString("SameHashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar salvar o arquivo..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 80.75.221.45_22005.
        /// </summary>
        internal static string SecondaryIP {
            get {
                return ResourceManager.GetString("SecondaryIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a segundos.
        /// </summary>
        internal static string SecondPlural {
            get {
                return ResourceManager.GetString("SecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a segundo.
        /// </summary>
        internal static string SecondSingular {
            get {
                return ResourceManager.GetString("SecondSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As configurações só serão aplicadas quando você fechar a caixa de diálogo de configurações..
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtro simples.
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciar.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chatlog analisado e copiado com sucesso para {0}.
        /// </summary>
        internal static string SuccessfulBackup {
            get {
                return ResourceManager.GetString("SuccessfulBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O parser precisa reiniciar para alternar para o servidor selecionado.
        ///
        ///Você gostaria de aplicar as alterações e reiniciar o aplicativo agora?.
        /// </summary>
        internal static string SwitchServer {
            get {
                return ResourceManager.GetString("SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://ucp.ls-chronicles.com.br.
        /// </summary>
        internal static string UCPLink {
            get {
                return ResourceManager.GetString("UCPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}..
        /// </summary>
        internal static string UpdateAbortTime {
            get {
                return ResourceManager.GetString("UpdateAbortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma nova versão do analisador de log de bate-papo está disponível no GitHub.
        ///
        ///Versão instalada: {0}
        ///Versão disponível: {1}
        ///
        ///Você gostaria de visitar a página de lançamentos agora?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização disponível.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}{1}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
